# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rKHhYqX-W9KftRFPoaU86cR-Py3XCMha
"""

from datetime import date

birthD = int(input("Enter your Birthday day "))
birthM = int(input("Enter your Birthday month "))
birthY = int(input("Enter your Birthday year "))

c_day = date.today().day
c_month = date.today().month
c_year = date.today().year

age_D = c_day- birthD
age_m = c_month - birthM
age_y = c_year - birthY

print(f"Your exact age is: {age_y}years {age_m}months {age_D}days")